const hotel = [
{
    id: '1',
    name: 'Warloff Hotel',
    location:'66 Hoog Street Polokwane',
    price:2500,
    image:require('../screens/images/pin1.jpg'),
    details:'Lorem ipsum dolor set amet',
    date:'25-02-22 - 27-02-22',
    status:'currently booked',
},
{
    id:'2',
    name:'Ubury Hotel',
    location: '15 Biccard Street Polokwane',
    price:1000,
    image:require('../screens/images/pin2.jpg'),
    details:'Lorem ipsum dolor set amet',
    date:'25-02-22 - 27-02-22',
    status:'Currently booked',

},
{
    id: '3',
    name: 'Damaris Hotel',
    location:'66 Hoog Street Polokwane',
    price:2500,
    image:require('../screens/images/pin3.jpg'),
    details:'Lorem ipsum dolor set amet',
    date:'25-02-22 - 27-02-22',
    status:'Currently booked',
},
{
    id:'4',
    name:'Stay Inn  Hotel',
    location: '15 Biccard Street Polokwane',
    price:1000,
    image:require('../screens/images/pin4.jpg'),
    details:'Lorem ipsum dolor set amet',
    date:'25-02-22 - 27-02-22',
    status:'Checked out',

},
{
    id: '5',
    name: 'Mooi Hotel',
    location:'66 Hoog Street Polokwane',
    price:2500,
    image:require('../screens/images/pin5.jpg'),
    details:'Lorem ipsum dolor set amet',
    date:'25-02-22 - 27-02-22',
    status:'Currently booked',
},
{
    id:'6',
    name:'Caiphus Hotel',
    location: '15 Biccard Street Polokwane',
    price:1000,
    image:require('../screens/images/pin6.jpg'),
    details:'Lorem ipsum dolor set amet',
    date:'25-02-22 - 27-02-22',
    status:'Currently booked',
},
{
    id: '7',
    name: ' Hotel Bella',
    location:'66 Hoog Street Polokwane',
    price:2500,
    image:require('../screens/images/pin7.jpg'),
    details:'Lorem ipsum dolor set amet',
    date:'25-02-22 - 27-02-22',
    status:'Checked Out',
},
{
    id:'8',
    name:'Mo Hotel',
    location: '15 Biccard Street Polokwane',
    price:1000,
    image:require('../screens/images/pin8.jpg'),
    details:'Lorem ipsum dolor set amet',
    date:'25-02-22 - 27-02-22',
    status:'Currently booked',

},
{
    id: '9',
    name: 'Elizabeth Hotel',
    location:'66 Hoog Street Polokwane',
    price:2500,
    image:require('../screens/images/pin9.jpg'),
    details:'Lorem ipsum dolor set amet',
    date:'25-02-22 - 27-02-22',
    status:'Currently booked',
},
{
    id:'10',
    name:'MacWaya Hotel',
    location: '15 Biccard Street Polokwane',
    price:1000,
    image:require('../screens/images/pin10.jpg'),
    details:'Lorem ipsum dolor set amet',
    date:'25-02-22 - 27-02-22',
    status:'Checked out',

},
{
    id: '11',
    name: 'Warloff Hotel',
    location:'66 Hoog Street Polokwane',
    price:2500,
    image:require('../screens/images/hotel11.jpg'),
    details:'Lorem ipsum dolor set amet',
    date:'25-02-22 - 27-02-22',
    status:'Checked out',
},
{
    id:'12',
    name:'Ubury Hotel',
    location: '15 Biccard Street Polokwane',
    price:1000,
    image:require('../screens/images/hotel1A.jpg'),
    details:'Lorem ipsum dolor set amet',
    date:'25-02-22 - 27-02-22',
    status:'Checked Out',

},
]

export default hotel